<a href="https://colab.research.google.com/github/ranamaddy/numpy/blob/main/Topic_01_Numpy_Creating_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Topic 01=Numpy Creating Arrays**


NumPy is a powerful Python library used for scientific computing, and it provides a convenient way to create arrays of various types and dimensions. Here are some examples of how to create arrays in NumPy:

# Creating a one-dimensional array:
To create a one-dimensional array, you can use the numpy.array function and pass in a list of values. For example, to create an array of integers from 0 to 4, you can use the following code:

import numpy as np

arr = np.array([0, 1, 2, 3, 4])

# Creating a two-dimensional array:
To create a two-dimensional array, you can use the numpy.array function and pass in a list of lists. For example, to create a 2x3 array of integers, you can use the following code:

import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5]])

# Creating a higher - dimensional Arrays

 Higher dimensional arrays are arrays that have more than one dimension or axis. In NumPy, higher dimensional arrays are used to represent multi-dimensional data, such as images, audio signals, and scientific data.

A one-dimensional array in NumPy is similar to a list in Python, but a higher dimensional array can be thought of as a list of lists, where each element in the list is itself a list or array.

For example, a two-dimensional array can be thought of as a matrix, where each row represents a set of values and each column represents a variable. Similarly, a three-dimensional array can be thought of as a cube, where each layer represents a set of values, and each row and column represents a variable.

Higher dimensional arrays in NumPy are created using the numpy.array function, which takes a list of values as input and returns a new NumPy array with the same values. The shape of the array specifies the number of dimensions and the size of each dimension.

NumPy also provides functions for creating arrays of zeros or ones with multiple dimensions, as well as for creating arrays with a specific data type and shape. These functions are useful when working with higher dimensional data, as they provide a convenient way to create arrays of the desired shape and data type.

Overall, higher dimensional arrays are an essential tool for working with multi-dimensional data in NumPy, allowing you to represent and manipulate data in a more efficient and intuitive way.

# Creating an array with a specific data type:

In NumPy, you can create an array with a specific data type using the numpy.array function and the dtype parameter. The dtype parameter specifies the data type of the array, and it can be used to create arrays of integers, floating-point numbers, complex numbers, and other types.

import numpy as np

arr = np.array([0.0, 1.0, 2.0], dtype=np.float64)

**(01)Creating a one-dimensional array:**









**Example** 

In [ ]:
import numpy as np
a = np.array([0, 1, 2, 3, 4])
print("output:",a)
print()
b=np.ndim(a)
print("one dimension array:",b)
print()
c = np.shape(a)
print("Shape:",c)

output: [0 1 2 3 4]

one dimension array: 1

Shape: (5,)


**(02) Creating a two-dimensional array:**

**Example** 

In [ ]:
import numpy as np
a = np.array([[0, 1, 2], [3, 4, 5]])
print("output:",a)
print()
b=np.ndim(a)
print("one dimension array:",b)
print()
c = np.shape(a)
print("Shape:",c)

output: [[0 1 2]
 [3 4 5]]

one dimension array: 2

Shape: (2, 3)


The code you provided is written in the Python programming language using the NumPy library. It creates a two-dimensional array named "a" using the NumPy array function and initializes it with the values 0, 1, 2, 3, 4, and 5.

The code then prints the contents of the "a" array using the print function.

Next, the code uses the NumPy ndim function to determine the number of dimensions in the "a" array and stores the result in a variable named "b".

After that, the code uses the NumPy shape function to determine the shape of the "a" array (i.e., the number of rows and columns) and stores the result in a variable named "c".

Finally, the code prints the values of the "b" and "c" variables using the print function.

**(03) Creating a three-dimensional array:**

**Example**

In [ ]:
import numpy as np
a = np.array([[[0, 1, 2], [3, 4, 5]],[[0, 1, 2], [3, 4, 5]]])
print("output:",a)
print()
b=np.ndim(a)
print("one dimension array:",b)
print()
c = np.shape(a)
print("Shape:",c)

output: [[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]

one dimension array: 3

Shape: (2, 2, 3)


The code you provided is written in the Python programming language using the NumPy library. It creates a three-dimensional array named "a" using the NumPy array function and initializes it with the values 0, 1, 2, 3, 4, and 5.

The code then prints the contents of the "a" array using the print function.

Next, the code uses the NumPy ndim function to determine the number of dimensions in the "a" array and stores the result in a variable named "b".

After that, the code uses the NumPy shape function to determine the shape of the "a" array (i.e., the number of elements along each dimension) and stores the result in a variable named "c".

Finally, the code prints the values of the "b" and "c" variables using the print function.







**(04) Creating a higher-dimensional array**

**Example**

In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8],ndmin=5)
print(a)

[[[[[1 2 3 4 5 6 7 8]]]]]


The code you provided creates a NumPy array called a with the values 1, 2, 3, 4, 5, 6, 7, and 8, and with five dimensions.

The np.array function is used to create a new array object in NumPy. In this case, the list [1, 2, 3, 4, 5, 6, 7, 8] is passed as input to the np.array function, creating a new NumPy array that contains these values. The ndmin parameter is set to 5, which means that the array should have at least five dimensions.

Since the input list contains only one set of values, NumPy adds extra dimensions with size 1 to meet the requirement of at least five dimensions. Therefore, the resulting array has five dimensions with shape (1, 1, 1, 2, 1).

The print function is then used to display the contents of the a array in the console. The output of the code should be:


[[[[[1],
     [2],
     [3],
     [4],
     [5],
     [6],
     [7],
     [8]]]]]
This shows the contents of the a array, which consists of the values 1, 2, 3, 4, 5, 6, 7, and 8 arranged in a five-dimensional structure with shape (1, 1, 1, 2, 1).

**(05) Creating an array with a specific data type:**

**Example 01**

In [ ]:
import numpy as np
a = np.array([0.0, 1.5, 2.0], dtype=np.float64)
print(a)

[0.  1.5 2. ]


Sure! This code creates a NumPy array called a with the values 0.0, 1.5, and 2.0, and with the data type np.float64, which specifies that the array should contain 64-bit floating-point numbers.

 

*  The first line imports the NumPy library and assigns the name np to it, which
is a common convention.

*   The second line creates a NumPy array called a with the values 0.0, 1.5, and 2.0, and with the data type np.float64.

*   The third line prints the contents of the **a;** array to the console.














**Example 02**

In [ ]:
import numpy as np
a = np.array([0.0, 1.5, 2.0], dtype=np.int64)
print(a)

[0 1 2]


The code snippet you provided creates a NumPy array named "a" containing the values 0.0, 1.5, and 2.0. The data type of the array is explicitly set to int64 using the dtype parameter in the np.array() function. However, since the values in the array are not integers, the decimal parts will be truncated and the resulting array will contain only the integer parts of those values (0, 1, and 2). The print() function is then used to display the contents of the array on the screen.